name: twasi-songrequests
author: Twasi Team
main: net.twasiplugin.songrequests.SongrequestPlugin
description: Songrequests with Spotify and YouTube
version: 1.0.0
commands:
  - sr
  - songrequest
  - skip
#  - wrongsong